apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: git-webhook-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/crempouji/git-webhook-app'
    targetRevision: HEAD
    path: .
    helm:
      parameters:
      - name: fullnameOverride
        value: gabriel-webhook-teste
      valueFiles:
        - values.yaml
      values: |-
        deployment:
          replicaCount: 2
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nginx-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true