apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: git-webhook-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/crempouji/git-webhook-app'
    targetRevision: HEAD
    path: .
    helm:
      parameters:
      - name: fullnameOverride
        value: gabriel-webhook-teste
      valueFiles:
        - values.yaml
      values: |-
        deployment:
          replicaCount: 2
        analysisTemplate:
          metrics:
            provider:
              prometheus:
                query: |
                  sum(irate(
                    istio_requests_total{reporter="source",destination_service=~"gabriel-webhook-teste-service",response_code!~"5.*"}[5m]
                  )) /
                  sum(irate(
                    istio_requests_total{reporter="source",destination_service=~"gabriel-webhook-teste-service"}[5m]
                  ))
        
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nginx-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true