apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: git-webhook-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/crempouji/git-webhook-app'
    targetRevision: HEAD
    path: .
    helm:
      parameters:
      - name: fullnameOverride
        value: gabriel-webhook-teste
      - name: namespace.name
        value: teste-nginx
      valueFiles:
        - values.yaml
      values: |-
        deployment:
          replicaCount: 2
        analysisTemplate:
          metrics:
            provider:
              prometheus:
                query: |
                  sum(irate(
                    istio_requests_total{reporter="source",destination_service=~"gabriel-webhook-teste-service.teste-nginx.svc.cluster.local",response_code!~"5.*"}[5m]
                  )) /
                  sum(irate(
                    istio_requests_total{reporter="source",destination_service=~"gabriel-webhook-teste-service.teste-nginx.svc.cluster.local"}[5m]
                  ))
        
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: teste-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: false