# Deployment Yaml Variables

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

deployment:
  replicaCount: 10
  podLabels:
    ola: myapp
    comovai: myapp1
  containerName: "argocd-reconciliation-container"
  image:
    repository: "nginx"
    tag: "alpine"
  resources:
    limits:
      memory: "128Mi"
      cpu: "500m"
    requests:
      memory: "70Mi"
      cpu: "200m"
  containerPort: 80

rollouts:
  enabled: true
  name: rollout-ref-deployment
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 10s}
        
service:
  type: NodePort
  name: crempouji-service

analysisTemplate:
  enabled: true
  metrics:
    name: success-rate
    successCondition: "result[0] >= 0.95"
    provider:
      prometheus:
        address: prometheus.istio-system.svc.cluster.local
        query: |
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{ .Values.service.name }}",response_code!~"5.*"}[5m]
          )) /
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{ .Values.service.name }}"}[5m]
          ))

istio:
  enabled: true
  gateway:
    host: "*"