# Deployment Yaml Variables

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

deployment:
  replicaCount: 10
  podLabels:
    ola: myapp
    comovai: myapp1
  containerName: "argocd-reconciliation-container"
  image:
    repository: "nginx"
    tag: "alpine"
  resources:
    limits:
      memory: "128Mi"
      cpu: "500m"
    requests:
      memory: "70Mi"
      cpu: "200m"
  containerPort: 80

rollouts:
  enabled: true
  name: rollout-ref-deployment
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 10s}