{{ if .Values.analysisTemplate.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ .Release.Name }}-analysis-template
spec:
  metrics:
  {{- with .Values.analysisTemplate.metrics }}
  - name: {{ .name }}
    successCondition: {{ .successCondition }}
    provider:
      prometheus:
        address: {{ .provider.prometheus.address }}
        query: |
        {{- with .provider.prometheus.query }}
        {{ toYaml . | nindent 10 }}
        {{- end -}}
  {{- end -}}
{{- end -}}