{{ if .Values.analysisTemplate.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "git-webhook-app.fullname" . }}-analysis-template
spec:
  args:
  - name: service-name
    value: {{ .Values.service.name }}
  metrics:
  {{- with .Values.analysisTemplate.metrics }}
  - name: {{ .name }}
    successCondition: {{ .successCondition }}
    provider:
      prometheus:
        address: {{ .provider.prometheus.address }}
        query: |
           sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}",response_code!~"5.*"}[5m]
          )) /
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}"}[5m]
          ))
  {{- end -}}
{{- end -}}