{{ if .Values.analysisTemplate.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "git-webhook-app.fullname" . }}-analysis-template
spec:
  metrics:
  {{- with .Values.analysisTemplate.metrics }}
  - name: {{ .name }}
    successCondition: {{ .successCondition }}
    provider:
      prometheus:
        address: {{ .provider.prometheus.address }}
        query: {{ .provider.prometheus.query | toYaml | nindent 10 }}
  {{- end -}}
{{- end -}}