apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "git-webhook-app.fullname" $ }}-dr
spec:
  host: {{ include "git-webhook-app.fullname" . }}-service
  subsets:
  - name: canary
    labels:
      {{- include "git-webhook-app.selectorLabels" . | nindent 6 }}
  - name: stable
    labels:
      {{- include "git-webhook-app.selectorLabels" . | nindent 6 }}