apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "git-webhook-app.fullname" . }}-vs
spec:
  hosts:
  - "*"
  gateways:
  - {{ include "git-webhook-app.fullname" . }}-gateway
  http:
  - route:
    - destination:
        host: {{ include "git-webhook-app.fullname" . }}-service.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.deployment.containerPort }}