apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "git-webhook-app.fullname" . }}-vs
spec:
  hosts:
  - "*"
  gateways:
  - {{ include "git-webhook-app.fullname" . }}-gateway
  http:
  - name: primary
    route:
    - destination:
        host: {{ include "git-webhook-app.fullname" . }}-service.{{ .Release.Namespace }}.svc.cluster.local
        subset: stable
      weight: 100
    - destination:
        host: {{ include "git-webhook-app.fullname" . }}-service.{{ .Release.Namespace }}.svc.cluster.local
        subset: canary
      weight: 0