{{ if .Values.rollouts.enabled }}
{{- with .Values.rollouts }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "git-webhook-app.fullname" $ }}-rollout
  labels:
  {{ include "git-webhook-app.labels" $ | nindent 4 }}
spec:
  replicas: {{ $.Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "git-webhook-app.selectorLabels" $ | nindent 6 }}
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "git-webhook-app.fullname" $ }}-deploy
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 10s}
        - analysis:
            templates:
            - templateName: {{ include "git-webhook-app.fullname" $ }}-analysis-template
        - setWeight: 40
        - pause: {duration: 20s}
        - analysis:
            templates:
            - templateName: {{ include "git-webhook-app.fullname" $ }}-analysis-templatez
        - setWeight: 60
        - pause: {duration: 30s}
        - analysis:
            templates:
            - templateName: {{ include "git-webhook-app.fullname" $ }}-analysis-template
      trafficRouting:
        istio:
          virtualService:
            name: {{ include "git-webhook-app.fullname" $ }}-vs
            routes:
            - primary
          destinationRule:
            name: {{ include "git-webhook-app.fullname" $ }}-dr
            canarySubsetName: canary
            stableSubsetName: stable
{{- end -}}
{{- end -}}